spring:
  application:
    name: springboot-mybatis-quickstart
  # 配置数据库的连接信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web01
    username: root
    password: 1234


mybatis:
  # 配置mybatis 的日志输出
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 指定XML映射配置文件的位置
  mapper-locations: classpath:mapper/*.xml



## 定义对象/Map集合
#user:
#  name: zhangsan
#  age: 18
#  gender: 男
#
## 定义数组/List/Set集合
#list:
#  - java
#  - game
#  - sport