spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework02
    username: root
    password: 1234

mybatis:
  # 配置mybatis 的日志输出
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 指定XML映射配置文件的位置
  mapper-locations: classpath:mapper/*.xml
